<?php
/**
 * @file
 * Code for the Kalamuna Picture Pane for responsive images across multiple pages
 */

include_once 'kala_picturepanes.features.inc';

/**
 * Implementation of hook_entity_info_alter()
 */
function kala_picturepanes_entity_info_alter(&$entity_info) {
  // Fieldable panel pane bundle to support picture panes
  $entity_info['fieldable_panels_pane']['bundles']['kala_picturepanes_jumbotron'] = array(
    'label' => t('Jumbotron images, 100% of the screen'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_image.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/kala_picturepanes_jumbotron',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
  $entity_info['fieldable_panels_pane']['bundles']['kala_picturepanes_full'] = array(
    'label' => t('Add full width responsive image, 12 columns'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_image.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/kala_picturepanes_full',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
  $entity_info['fieldable_panels_pane']['bundles']['kala_picturepanes_half'] = array(
    'label' => t('Add half width responsive image, 6 columns'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_image.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/kala_picturepanes_half',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
  $entity_info['fieldable_panels_pane']['bundles']['kala_picturepanes_quarter'] = array(
    'label' => t('Add quarter width responsive image, 3 columns'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_image.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/kala_picturepanes_quarter',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}


/**
 * Implements hook_preprocess_panels_pane().
 */
function kala_picturepanes_preprocess_panels_pane(&$variables){
  if(isset($variables['content']['#bundle'])){
    $bundle = $variables['content']['#bundle'];
    if(strpos($bundle, 'kala_picturepanes') === 0){

      $variables['theme_hook_suggestions'][] = 'fieldable_panels_panes__kala_picturepanes';

    }

  }
}




/**
 * Implements hook_theme_registry_alter().
 */
function kala_picturepanes_theme_registry_alter(&$theme_registry) {
  $theme_registry['fieldable_panels_panes__kala_picturepanes'] = array(
    'template' => drupal_get_path('module', 'kala_picturepanes') . '/templates/fieldable-panels-panes--kala-picturepanes',
    'theme path' => drupal_get_path('module', 'kala_picturepanes'),
    'type' => 'module',
  );
}
